"""Contracts for source frontends and future output adapters, without implementations."""
from __future__ import annotations
from typing import Any, Protocol
from .schema import CanonicalWorldModel

class PhotoFrontendAdapter(Protocol):
    def to_canonical_world_model(self, artifact: Any) -> CanonicalWorldModel: ...
class VideoFrontendAdapter(Protocol):
    def to_canonical_world_model(self, artifact: Any) -> CanonicalWorldModel: ...
class CrossModalRegistrationEngine(Protocol):
    def align(self, photo_model: CanonicalWorldModel, video_model: CanonicalWorldModel) -> CanonicalWorldModel: ...
class VectorExportAdapter(Protocol):
    def export_vector(self, model: CanonicalWorldModel) -> str: ...
class JsonExportAdapter(Protocol):
    def export_json(self, model: CanonicalWorldModel) -> str: ...
